### ISSUE TITLE
Text-Overlay in WASM rendering

### ISSUE THREAD

**Issue by inzanez** [paulo-coutinho/pdfium-lib#32]
It would definitely be nice to get a text overlay (or however selectable text is generated usually?) so that the viewer doesn't just display the image, but also selectable text.

**Comment by paulo-coutinho** [comment]
Hi,

How it works?

Because today the code generate some images from the pages.

**Comment by inzanez** [comment]
Well, that's the question to answer I would assume. But assuming that the Chromium integrated PDF reader is based on PDFium, they will do the same that you are currently doing with WASM (render the images), but also render the font somehow, somewhere.
You would have to check with other existing PDF readers how it's done, but I guess that you could render the Font on another layer/canvas. I haven't had time to investigate that issue.

**Comment by paulo-coutinho** [comment]
Hi,

You can call the APIs of other samples, like this:
https://github.com/benjinus/android-support-pdfium/blob/master/library/src/main/java/org/benjinus/pdfium/PdfiumSDK.java

The aim of this project is not make a full hyper mega PDF reader, but compile and make it work with any sample.

Any user can download and make a better reader and/or submit it here.

Can i close it?

**Comment by cetinsert** [comment]
@paulo-coutinho – I agree that we, the people of the web, need a place for a solid, well-maintained WASM build of `PDFium` kept up-to-date with upstream and this repository is already very valuable in providing just that. Scope creep might not only increase the development burden but also eventually lead to leaving the project unmaintained due to lack of developer power. I would hate to see this repository lose its clear cut definition, try to become everything for everyone but slowly fail to deliver on community requests and get abandoned.

---

@inzanez – https://lab.webpdf.dev/inzanez.html – here is an example page that I froze in time just for you!
(Left is `PDFium` `♊` (looks like the color of WASM and the letter `ㅍ`) , right side `🦊` `PDF.js`.)
(Declarative HTML API documentation: https://webpdf.pro/#📖)

`PDF.js` does indeed create a text layer of invisible `<span>` elements that are overlaid on top of the `<canvas>` or `<svg>` images. I am working on https://WebPDF.pro – a commercial set of web components / custom elements that simplify working with `<pdf-file>`s and `<pdf-page>`s dead-simple with a declarative HTML API and I do use a hybrid approach: use `PDFium` for `<canvas>` renders (optionally) and `PDF.js` for everything else (for now and the foreseeable future). `PDFium` support will officially release once issue https://github.com/paulo-coutinho/pdfium-lib/issues/33 has been resolved.

---

Both of you, @inzanez and @paulo-coutinho, are eligible for life-time ever-green free licenses to https://WebPDF.pro! Just get in touch with me at `open.source@pdf.ist` by email and I will send you a single reply with your keys! Your email addresses will not be shared with 3rd parties or used for marketing (both of which I don't have and once I do, you will not be among the people I target by email).

**Comment by inzanez** [comment]
Yes, I can see that approach only sticking with the lib. That was merely a suggestion of what else will definitely be hard for a user of such a library to create a usable PDF viewer.

@cetinsert Oh, I really like your project, that looks quite promising. Many thanks for your kind offer of a free license key! I will definitely get back to you once we progress in our attempts :-)

**Comment by paulo-coutinho** [comment]
Nice @inzanez.

If you have questions, suggestions or bug report feel free to report here please. Everything is important.

Thanks.
